name: voice_command_search_plugin
description: A compact voice search widget plugin for Flutter
version: 0.0.1
homepage: https://github.com/hongsw/voice_command_search_plugin

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.voice_search_plugin
        pluginClass: VoiceSearchPlugin
      ios:
        pluginClass: VoiceSearchPlugin

license: MIT

repository: https://github.com/hongsw/voice_command_search_plugin
issue_tracker: https://github.com/hongsw/voice_command_search_plugin/issues
documentation: https://github.com/hongsw/voice_command_search_plugin/wiki